num_moves_range:
  min: 10
  max: 150

puzzle_default_moves:
  2x2: 10
  3x3: 25
  4x4: 40
  5x5: 60
  6x6: 80
  7x7: 90
  8x8: 100
  9x9: 110
  10x10: 120
  11x11: 130

puzzle_type_list:
  - 2x2
  - 3x3
  - 4x4
  - 5x5
  - 6x6
  - 7x7
  - 8x8
  - 9x9
  - 10x10
  - 11x11

min_window_size:
  width: 400
  height: 230
